spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foro
    username: ${DB_USER_MYSQL}
    password: ${DB_PASSWORD}

server:
  error:
    include-stacktrace: never

#api:
#  security:
#    secret:
#      ${JWT_SECRET}